### ISSUE TITLE
LivePage disables after reload

### ISSUE THREAD

**Issue by L3V147H4N** [MikeRogers0/LivePage#100]
Im using LivePage in a (NodeJS/FeathersJS, React) prpject that compiles with webpack and it reloads when webpack compiles the JS but after the reload LivePage disables itself

**Comment by MikeRogers0** [comment]
Thanks for reporting! I need some additional information to help me recreate this:

1. When you open the console in Chrome are there any errors being thrown while using the above?
2. Do you have a copy of the code I can run my end to reproduce the error?

**Comment by L3V147H4N** [comment]
my repository is currently private, I share it once I've make sure I can.
(as a side note) I recently started using the latest version of webpack and now the extension is working correctly but I don't know if it has anything to do with it, I'll do further testing

**Comment by L3V147H4N** [comment]
The problem seems tide to the different routes, I configure `localhost:3030` to be live but anything beyond it like `localhost:3030/something` doesn't seem to work

**Comment by MikeRogers0** [comment]
Could be related to #98 - I'll investigate more this week :)

**Comment by MikeRogers0** [comment]
@L3V147H4N Good news! I was able to track down what was causing the issue (URLs with port numbers were being considered as external resources). I've pushed a fix to the store.

Thank you so much for reporting!
