### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by JChanceHud** [MikeRogers0/LivePage#101]
I'm having trouble purchasing through the google store (obscure payment error) and instead downloaded the source and installed manually.

If you could put some sort of donation system in place I'd be happy to send a donation your way. I'd prefer Ethereum or Bitcoin, but Paypal works too, this tool is super helpful for rapid prototyping/development.

Just a thought, thanks for the hard work.

**Comment by MikeRogers0** [comment]
I used to have a donation link, but no one ever clicked it so I removed it.

To be honest, your kind words mean much more to me then any donation! I love hearing from developers that LivePage is helping them build!
