### ISSUE TITLE
Doesn't work with Jekyll

### ISSUE THREAD

**Issue by mvasin** [MikeRogers0/LivePage#104]
Does not pull in the changes when Jekyll serves the site with `bundle exec jekyll serve`.

**Comment by MikeRogers0** [comment]
I use LivePage to build a few sites with Jekyll, so I'll need some more
information to recreate the issue.

Which version of Jekyll are you using? Do you have any logs or a repo I can
debug with?

**Comment by mvasin** [comment]
I've already canceled the order on chrome extensions store right after I saw it didn't work what I bought it for, but your quick response looks promising, so I bought it once again just to make sure I give you right reproduction steps. Here they are:

[Install Jekyll](https://jekyllrb.com/docs/installation/)
```shell
# bootstrap new site
jekyll new reload-test

cd reload-test

# make sure ruby dependencies are there
bundle

# start the server
bundle exec jekyll serve
```
Now, for instance, edit `about.md` in the current `reload-test` directory and see that the extension does not catch any changes, but you can see them by refreshing the browser page manually.

I'm on a mac 10.12.6 and jekyll version is 3.5.2.

**Comment by MikeRogers0** [comment]
Awesome thank you! This sounds pretty serious, I'll investigate ASAP!

**Comment by MikeRogers0** [comment]
Hi again! I've just attempted to reproduce this locally & everything worked as expected ( Here is a video https://www.youtube.com/watch?v=IJ6vpuN3rxw&feature=youtu.be ).

I suspect another extension could be interfering with LivePage, if you provide any console output I'd appreciate it!

**Comment by mvasin** [comment]
Oh, dammit, I missed the 'press the icon to turn it on' thing! I just didn't have this in mind, thinking that if the extension is on, it's on. I did watch the introductory video, but just didn't pay attention.

It totally works, sorry for bothering.

**Comment by MikeRogers0** [comment]
Hah! I'll make a note of this, I'm certain other users will have run into this also :)

**Comment by mvasin** [comment]
Yeah, a hint on the first activation of the extension would be wonderful.

Thanks for quick response and GLWS :)
