### ISSUE TITLE
Doesn't work with Vue

### ISSUE THREAD

**Issue by mvasin** [MikeRogers0/LivePage#106]
I'm pretty happy with the experience overall, but this file, saved to disk, and opened in chrome, with permission to access files on disk granted, does not update. Change message text for yourself.

```
<!DOCTYPE html>
<html>
<head>
  <title>My first Vue app</title>
  <script src="https://unpkg.com/vue"></script>
</head>
<body>
  <div id="app">
    {{ message }}
  </div>

  <script>
    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })
  </script>
</body>
</html>
```

**Comment by MikeRogers0** [comment]
Hi @mvasin ! I just tested this my end & found the issue.

In the LivePage options ( right click on the icon & click options ), under "Advanced Settings" uncheck "Ignore inline Javascript". Once this is unchecked you should see LivePage working as you expect :)

<img width="786" alt="inline-js" src="https://user-images.githubusercontent.com/325384/30124229-665649f6-932c-11e7-83dd-d99e601a5769.png">

By default this is enabled as lots of WordPress users put timestamps in their inline JavaScript.

**Comment by mvasin** [comment]
Yes, it works, thank you.
