### ISSUE TITLE
Import css file with relative path throws 404

### ISSUE THREAD

**Issue by amedov-denis** [MikeRogers0/LivePage#112]
If i have a index.css and import other files like: `@import 'css/other.css'`

In this usecase it's throwing a 404 because it tries to load the resource from : "root/css/other.scss".

But if i import root-relative like `@import '/theme/directory/css/other.css'`,then it's working.

It should be more generic, because the root path can  can be completely different in several environments.
And it's not a good approach for me to change something before pushing to production.

**Comment by MikeRogers0** [comment]
Oh no, that's not good. I'll investigate this @amedov-denis ASAP & keep you updated!

**Comment by amedov-denis** [comment]
@MikeRogers0 thanks for investigating. Do you think you can fix it in the next time?

**Comment by MikeRogers0** [comment]
@amedov-denis No problem, sorry it's taking me a while to solve this one!
I'm aiming to have this fixed before before Xmas.

**Comment by MikeRogers0** [comment]
@amedov-denis I've opened a PR adding files matching the issue you're describing ( https://github.com/MikeRogers0/LivePage/pull/113/files ). 

When I run `php -S 127.0.0.1:8000 -t demo/` to open those HTML like a web server, then visit `http://127.0.0.1:8000/subdir/` and run LivePage I don't see any 404 errors.

Could you confirm that those files match the issue you're describing / possibly send me a URL to where the error is noticeably occurring?

**Comment by amedov-denis** [comment]
Yes of course, because in this special case "relative" and "root-relative" is the same. 
But if you wrap `index.css` and `css` in a `src` folder, then it's not working any more.
Try this file structure:

root
└── index.html
└── src
    └── css
     |    └── imported.css
    └── index.css

This should throw a 404 because it tries to import `/css/imported.css` instead of `/src/css/imported.css`

**Comment by MikeRogers0** [comment]
@amedov-denis Good news!!! I recreated the issue & got a fix written! I'll deploy once the automated test pass. It should reach your browser within 12 hours.

I really appreciate your help & patience with this one 👍 If we cross paths make sure to make me buy you a beverage :)

**Comment by amedov-denis** [comment]
@MikeRogers0 Great, thank you very much for your effort :)
