### ISSUE TITLE
TypeError: Object false has no method 'checkBatch'

### ISSUE THREAD

**Issue by GloverDonovan** [MikeRogers0/LivePage#25]
I got the following error:
Uncaught TypeError: Object false has no method 'checkBatch' (anonymous function)

Maybe because of two loading instances? The html tag had 2 livepage-loading classes.

**Comment by GloverDonovan** [comment]
Bumping this. Has this issue been fixed and can I close it?

**Comment by MikeRogers0** [comment]
I've not been able to reproduce it (Though I've recently removed LESS from LivePage). If you can't reproduce it your end feel free to close.

**Comment by GloverDonovan** [comment]
Alright. I don't use Less anymore but Sass now. Going to close this. (:
