### ISSUE TITLE
LESS reloading crashes

### ISSUE THREAD

**Issue by KenRmk** [MikeRogers0/LivePage#29]
Works perfectly with html and css, but when i update less file it crashes.
It notices the change and logs it in the console ( ["refreshing", "........*.less", liveResource] ) and then it crashes saying this
Uncaught ReferenceError: $LivePageLESS is not defined livepage.js:405
LiveResource.refresh livepage.js:405
LiveResource.check livepage.js:329
livePage.check livepage.js:246
livePage.checkBatch livepage.js:214
(anonymous function) livepage.js:217

**Comment by wrick17** [comment]
The issue is still there. Am I missing something?

**Comment by MikeRogers0** [comment]
I'll investigate again, I imagine the error as crept back in.

**Comment by oguresic** [comment]
You can fix it: this lines are missing at the end of file js/less-1.4.1.min.js:

// Put the less stuff into a global variable, so the live page extension can access it.
var $LivePageLESS = window.less;

**Comment by oguresic** [comment]
And i found out that less-1.3.0.min.js is working, but less-1.4.1.min.js in current LivePage is not refreshing less files ... so you have to exchange it manually to get it working.

**Comment by MikeRogers0** [comment]
I decided to remove LESS from 1.5.2. LESS in the browser has its own polling update built in now, so it would be a duplication of efforts for LivePage to support it. That said, if users are using the server side compilers with watchers LivePage should pick up on the changes and work normally.
