### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated 

### ISSUE THREAD

**Issue by JacopKane** [MikeRogers0/LivePage#34]
Not important yet but just for heads up my chrome dev tool is throwing this warning:
```
livepage.js:297:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/. 
```
![screenshot 2015-02-01 00 44 19](https://cloud.githubusercontent.com/assets/68406/5990143/f2820f7c-a9ab-11e4-80f7-026d6c750ba7.png)

**Comment by MikeRogers0** [comment]
Thanks for the heads up, hopefully going to have an update out by the end of the month to fix this and the other bugs :)
