### ISSUE TITLE
Get Internal server error 500

### ISSUE THREAD

**Issue by kriskrukkert** [MikeRogers0/LivePage#35]
Hello,

The extension does not work for me and get the following error:

GET http://www.theloop.nl/framework/?livePage=1425555753572 500 (Internal Server Error)livepage.js:301 LiveResource.checklivepage.js:246 livePage.checklivepage.js:214 livePage.checkBatchlivepage.js:217 (anonymous function)

 What am I doing wrong?

**Comment by MikeRogers0** [comment]
http://www.theloop.nl/framework/ - Is that the URL you're trying to make live? It looks like that file has a PHP error on it, hence it's returning a 500 error.

**Comment by kriskrukkert** [comment]
The PHP error is gone now. Now it gives me the following error:

Uncaught ReferenceError: $LivePageLESS is not defined

**Comment by MikeRogers0** [comment]
That looks like an error from the extension, I'm deploying a patch tomorrow morning to deal with the LESS issue.

**Comment by kriskrukkert** [comment]
Oke I hope that it will fix my problem. Im looking foward using the extension. Thnx for the support!

**Comment by MikeRogers0** [comment]
Ok fixed deployed to Chrome Web Store, hopefully you should be A-OK from now on :)
