### ISSUE TITLE
Increase Polling Setting time?

### ISSUE THREAD

**Issue by abzence** [MikeRogers0/LivePage#37]
I'm wondering if there is some way to increase the polling setting time to let's say every 5 - 10 minutes?

I'm trying to use it as a way of displaying live info on a remote screen that only needs to update in 5 minutes intervals and the 1000ms seems to decrease the performance of the slide show that displays the data.

**Comment by MikeRogers0** [comment]
Right now there is not. In the next version I'll add a free text field :)

**Comment by abzence** [comment]
Thank you. That would be awesome :)
