### ISSUE TITLE
No Refresh On Editing Indirectly Referenced Files Such As Angular Directives

### ISSUE THREAD

**Issue by jwbats** [MikeRogers0/LivePage#38]
LivePage only seems to fresh when it detects changes to the index file and the files it directly references (scripts and css).

It does not refresh on editing Angular directives.

I am using this on my localhost and I would like this plugin to watch my whole folder.

**Comment by MikeRogers0** [comment]
LivePage is probably not the extension for you, its more designed for simple web page design & not web apps.
