### ISSUE TITLE
NotFoundError: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by helarqjsc** [MikeRogers0/LivePage#39]
Got the following error while trying to update CSS:
```
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
LiveResource.refresh @ live_resource.js:140
xhr.onreadystatechange @ live_resource.js:74
XMLHttpRequest.send (async)LiveResource.check @ live_resource.js:79
livePage.check @ livepage.js:180
livePage.checkBatch @ livepage.js:163
(anonymous function) @ livepage.js:181
setTimeout (async)(anonymous function) @ livepage.js:181
xhr.onreadystatechange @ live_resource.js:56
XMLHttpRequest.send (async)LiveResource.check @ live_resource.js:79
livePage.check @ livepage.js:180
livePage.checkBatch @ livepage.js:163
(anonymous function) @ livepage.js:181
setTimeout (async)(anonymous function) @ livepage.js:181
xhr.onreadystatechange @ live_resource.js:56
```
Any ideas why it happens and how it can be fixed?

**Comment by MikeRogers0** [comment]
Oh weird - I'll investigate. Do you have a copy of the page you where making live available?

**Comment by helarqjsc** [comment]
Well, I got the same error on all the pages I've tested so far, but here is the one I got the error initially on: http://bmicalculators.com/

**Comment by MikeRogers0** [comment]
Awesome! I'm planning a coding session this weekend to squash this bug :+1:

**Comment by helarqjsc** [comment]
I've figured out why the error occurs. This part expects that the original `<link>` exists in the `<head>` tag:
```
$livePage.head.insertBefore(cssElement, this.element);
$livePage.head.removeChild(this.element);
```
In my case `<link>` was at the bottom of the `<body>`, that's why it complained that `The node before which the new node is to be inserted is not a child of this node.`

To fix it something like that needs to be done instead:
```
$livePage.head.insertBefore(cssElement, $livePage.head.lastChild);
$livePage.head.removeChild(this.element);
```
That should work fine, right?

**Comment by MikeRogers0** [comment]
+1! 

That should work, though I'll try and update it to not expect the link tag to be in the `<head>` element (Though I'm currently on the road, it might take a week or 2 for me to get it to live).

**Comment by MikeRogers0** [comment]
IIRC this was patched in [1.5.3](https://github.com/MikeRogers0/LivePage/releases/tag/1.5.3)

**Comment by helarqjsc** [comment]
I still get the exact the same error in the exact same circumstances in 2.0.1, so I don't think it was fixed.

**Comment by MikeRogers0** [comment]
@helarqjsc I've pushed 2.1.0 to the Chrome Store. Can you confirm the fix works for your use case for me? :)
