### ISSUE TITLE
Duplicate Domain in URL with Leading Slash

### ISSUE THREAD

**Issue by eightygrit** [MikeRogers0/LivePage#40]
When rewriting a domains and paths, the domain is duplicated and a leading slash is added, causing the Chrome extension to 404 every file and eventually reload ever 2-3 seconds. 

In my case, a URL like `http://client.dev/main.css` becomes `/http://client.dev/main.css`. That leading slash then causes the browser to request `http://client.dev/http://client.dev/main.css`. 

I suspect this comes from the way you re-join the `parts` of the `stack` var around livepage.js:47.

**Comment by MikeRogers0** [comment]
Thanks for reporting this, I'm planning a coding session this weekend to squash this bug :+1:
