### ISSUE TITLE
Can get contents of html pages but not css pages

### ISSUE THREAD

**Issue by amlwwalker** [MikeRogers0/LivePage#41]
**If you havent read this answer yet, please note I have edited it with a quick fix, however I don't think it is a good thing**
Hi 
This is a great little plugin by the way. I am trying to print out the contents of the file that has changed. This works fine when the file type that changed is html, however when its javascript or css, it doesnt seem to get set.

In `LiveResource.prototype.check()` there is the line `_this.response = _this.tidyCode(this.responseText);`. If I `console.log(this.responseText)` it is not set to anything. Whats interesting is it does notice the file change and refresh the page. Any ideas why this might be happening?

EDIT: Looking at the inspector in Chrome, I can see the css file being loaded: 

![image](https://cloud.githubusercontent.com/assets/2920180/10865229/0adbadc6-7ffd-11e5-85a6-b5daf68ce092.png)

I am interested that its being loaded over HTTP HEAD  protocol, and the file has no content/response: 

![image](https://cloud.githubusercontent.com/assets/2920180/10865237/43be5814-7ffd-11e5-8f71-db00feb24733.png)

even though the file loaded fine: 

![image](https://cloud.githubusercontent.com/assets/2920180/10865239/502aae40-7ffd-11e5-8ab3-90b442a86302.png)

EDIT: OK I have fixed it, but I am suspicious as to my fix. By changing the line:

```
this.method = 'HEAD';
```

to 
```
this.method = 'GET';
```
It now works. However Im not sure why it was set to `HEAD` for all files not html and therefore what I have undone by changing that? I think it will just slow down the connection but without the body Im not sure why we were checking the headers only?

**Comment by MikeRogers0** [comment]
I think the lines of code you're talking about [is this bit](https://github.com/MikeRogers0/LivePage/blob/9021d21e7b8611cdf65ed3bf360aa47dce64e7c5/js/injected/live_resource.js#L11-L14):

```javascript
this.method = 'HEAD';
if (this.type == 'html' || this.url.indexOf('file://') == 0 || $livePage.url.indexOf('file://') == 0 || $livePage.options.use_only_get == true) {
  this.method = 'GET';
}
```

It's set to HEAD by default as l suspect a lot of users of LivePage are in a production like environment, where the server should honour the 200/302 status types (Which will reduce the bandwidth of each request). 

However, I had also added in the [option on the settings page](https://github.com/MikeRogers0/LivePage/blob/9021d21e7b8611cdf65ed3bf360aa47dce64e7c5/options.html#L81) to use only GET requests.
