### ISSUE TITLE
Add support for additional file extensions

### ISSUE THREAD

**Issue by ashthecreative** [MikeRogers0/LivePage#42]
For a project I'm currently working on, I'm using .shtml files which aren't being detected as being updated. Maybe a feature where you can list your own extensions to watch would be useful.

**Comment by MikeRogers0** [comment]
That would be pretty cool :) Can you post me a code sample of how you're using .shtml files?

**Comment by MikeRogers0** [comment]
This can be handled by adding `rel="livePage"` to the link that you want to be made "live. For example:
```
<link rel="livePage" href="/path/to/file.shtml" />
```
