### ISSUE TITLE
Using IntelliJ to debug HTML/Javascript, LivePage errors out

### ISSUE THREAD

**Issue by shadybones** [MikeRogers0/LivePage#43]
In IntelliJ, you can debug javascript in the browser by having the IDE host the pages and connecting to Chrome dev apis. When doing this, LivePage does not work, and prints out the following errors:

Uncaught TypeError: $livePage.checkBatch is not a function
  (anonymous function)  
Uncaught TypeError: Cannot read property 'refresh_rate' of undefined
  (anonymous function)  
  xhr.onreadystatechange

I really can't say any more than this, other than it happens no matter what page I try to debug, so duplicating it shouldn't be a problem. I'm using the enterprise edition of IntelliJ, so I can't say if it happens on the Community edition.

Info: OSX 10.8, Chrome 49, LivePage 1.6.1, IntelliJ 15.0.1

**Comment by MikeRogers0** [comment]
Oh weird - I'll investigate this weekend, though I don't use IntelliJ so it might take me a while to figure out the crooks of the issue.

**Comment by MikeRogers0** [comment]
I wasn't able to recreate this issue on IntelliJ Community edition / WebStorm. I'm going to leave this ticket open incase anyone else can shed some light on this.

**Comment by Hativ3** [comment]
I don't use IntelliJ, but often get the same errors on Chrome's developer tools console.

> Uncaught TypeError: $livePage.checkBatch is not a function(…)
> (anonymous function) @ livepage.js:225

Code in line 225 is:
`setTimeout(function() { $livePage.checkBatch(); }, $livePage.options.refresh_rate);`

While I'm debugging a javascript application other errors are really annoying.

Chrome 54 on Windows, LivePage 2.2.3

**Comment by MikeRogers0** [comment]
@Hativ3 thanks for the report :)

Can you provide some more details of your setup? e.g. a repo I can run to figure out whats up?

**Comment by MikeRogers0** [comment]
I'm going to rescope '$livePage' to 'window.$livePage' I think that should solve this issue for good :)

**Comment by Hativ3** [comment]
Unfortunately I can't provide a repo. but I think it's a general issue and rescoping may be does the trick. I'll test it as soon you released a update. Thank you!

**Comment by MikeRogers0** [comment]
@Hativ3 I've pushed 2.3.0 to production, it should role out to all users in the next 24 hours :)

**Comment by Hativ3** [comment]
No errors anymore, great! Thank you!
