### ISSUE TITLE
Don't monitor 404 files

### ISSUE THREAD

**Issue by CodinCat** [MikeRogers0/LivePage#49]
Currently, LivePage will keep yielding errors if there is a 404 file: 

![screenshot](https://cloud.githubusercontent.com/assets/3193344/16302803/bcfb813e-397f-11e6-9b57-5ced134f6206.png)

I think this can be an option:
Should LivePage ignore non-existing files

so we can get rid of these errors in some cases.

**Comment by MikeRogers0** [comment]
Thank for you reporting this bug @CodinCat :)

I'm intending to publish the bugfix to the Chrome Store (which will then push to your browser) by Friday 24th of June.
