### ISSUE TITLE
Page not reloaded on CSS change with multi-step build process

### ISSUE THREAD

**Issue by arechsteiner** [MikeRogers0/LivePage#57]
LivePage stopped working for me with CSS files. I am not sure of the exact cause, and I don't know how to debug or troubleshoot this plugin. 

I have a suspicion though: My build process involves trans-piling multiple CSS files from SCSS sources. I think it stopped working when I started doing the steps sequentially instead of concurrently. I suspect that LivePage reloads when the first CSS is built, and then does not load the second new CSS because it's still building. 

I've tried with a higher interval (500ms and 2000ms) but it doesn't help. The page is not reloaded when the CSS changes.

If I modify the CSS file directly, LivePage works.

**Comment by arechsteiner** [comment]
I want to add that I also run into trouble when I use LivePage with "JavaScript" enabled, for similar reasons: LivePage starts reloading because the JavaScript is already built, but not the CSS. Then the page is all messed up because the CSS is not in place. 

I think a possible approach to all of this would be a possible time delay between the trigger and the actual reload, to enable the build process to finish before reloading. My entire build is about 2 seconds long at this point.

**Comment by MikeRogers0** [comment]
That sounds like quite an annoying problem, out of interest what are you using to transpile your code?

> I think a possible approach to all of this would be a possible time delay between the trigger and the actual reload.

Sounds good! I'm happy to implement this kind of feature in the next build :)

**Comment by arechsteiner** [comment]
I use gulp with gulp-sass, which ultimately uses libsass (I think). There's some other stuff going on as well, such as copying files around and things like that. Minification, linting, autoprefixer, etc.

I'm happy to hear you're willing to implement this. At the moment I'm refreshing the browser manually which is not the idea of the plugin of course.

**Comment by MikeRogers0** [comment]
I haven't forgotten about this, I'm hoping to get some time to work on this during this weekend :)

**Comment by MikeRogers0** [comment]
https://github.com/MikeRogers0/LivePage/tree/feature/reload-delay - Got it working :) I'm going to tidy up the settings page before this is released, it looks a little gnarly right now.

**Comment by arechsteiner** [comment]
I have now worked around this issue using

      <link rel="livePage" href="/reload.html" />

I have disabled CSS/JavaScript watching and instead in my build process, as a very last step, I update reload.html so LivePage is triggered only after the build is finished.

**Comment by MikeRogers0** [comment]
@arechsteiner Awesome! 

I'm still figuring out a good way to implement the reload delay without confusing users wouldn't use the feature. I might make it a shadow option (so you open the terminal on the settings page to enable it), what do you think?

**Comment by arechsteiner** [comment]
If I were you, I would add a setting like the polling setting, possibly a new category

## Reload settings

- [ ] Attempt to persist scroll X/Y positions
- Minimum delay before reloading: `0` ms

  _Set a delay if you want LivePage to wait before reloading the page. This is useful when you have a build process that needs to finish before a reload is triggered._

**Comment by MikeRogers0** [comment]
@arechsteiner Sounds cool. I'll try and get some updates done this weekend (I'm flying though, so bear with me) :)
