### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by MikeRogers0** [MikeRogers0/LivePage#58]
It could be cool to make a landing page like https://askjelly.com/extension/?ref=producthunt - though I'm not sure how inline installs would work if it's paid for / free trail.

**Comment by andyrichardson** [comment]
@MikeRogers0 I can do a quick design over the next couple of days if you're interested?

**Comment by MikeRogers0** [comment]
@andyrichardson That would be awesome! Want me to drop you an email to talk ideas?

**Comment by andyrichardson** [comment]
@MikeRogers0 Go for it

**Comment by MikeRogers0** [comment]
As mentioned by @andyrichardson maybe something like https://onepagelove.com/paws-for-trello

**Comment by andyrichardson** [comment]
Its a very basic example but maybe something along these lines might work.

![livepage landing page](https://cloud.githubusercontent.com/assets/10779424/17519613/9cd9de8e-5e44-11e6-95c0-2e75645884d4.png)

**Comment by MikeRogers0** [comment]
Awesome dude! I'll get coding up & ping you a repo :)

**Comment by MikeRogers0** [comment]
https://github.com/MikeRogers0/LivePage-landing - Sorry it took me a few days to get something up. But I got started with a fairly basic middleman site. 

Hopefully I get a bit more time this week to make it look a lot prettier / look more closer to @andyrichardson  mockup.

**Comment by andyrichardson** [comment]
@mikerogers0 thanks for the update. I'll watch the repo and start getting involved after your initial push.

**Comment by MikeRogers0** [comment]
https://livepage.mikerogers.io/ - Looking good! I'm closing this ticket now :)
