### ISSUE TITLE
Cannot read property 'refresh_rate' of undefined

### ISSUE THREAD

**Issue by codeandcats** [MikeRogers0/LivePage#70]
Hi Mike,

I freaking love this extension so much. Thanks for creating it. There's just one niggling problem I have with it constantly which is very frustrating when debugging an web app I'm working on. LivePage will frequently pop up this error when reloading a page:

```
livepage.js:241 Uncaught TypeError: Cannot read property 'refresh_rate' of undefined
```

Here is the offending code:
```javascript
/*
 * Triggers a resource check.
 */
livePage.prototype.check = function() {
  // Que up the next resource, if it dosen't exist start again.
  this.lastChecked++;
  if (this.resources[this.lastChecked] == undefined) {
    this.lastChecked = 0;
    if (this.resources[this.lastChecked] == undefined) { // Nothing left to check
      window.$livePage.options.enabled = false;
      return;
    }
  }

  this.resources[this.lastChecked].check(function(){
    setTimeout(function() { 
      if( typeof(window.$livePage.checkBatch) == "function" ){
        window.$livePage.checkBatch();
      }
    }, window.$livePage.options.refresh_rate); // <----- ERRORS ON THIS LINE
  });
}
```

Note that is doesn't occur every time, but most of the time.

If you were able to push out a simple fix for this, it would solve this long running issue I've had with this extension and effectively make it perfect imo.

**Comment by MikeRogers0** [comment]
Hey I've struggled to recreate this error ( see #46 ). Could you send me some details about you setup to help me recreate?

**Comment by codeandcats** [comment]
Interesting, the project I get the error in is also using React. I'll do some more investigation, time allowing, sometime over the next couple days and maybe come up with a barebones project demonstrating the issue.

**Comment by MikeRogers0** [comment]
That would be amazing! Also you wouldn't happen to be in Sydney would you?

**Comment by codeandcats** [comment]
No worries at all. Actually I'm in Melbourne.

**Comment by MikeRogers0** [comment]
Ah darn, I'm in Sydney for the next 2 weeks :)

**Comment by codeandcats** [comment]
Oh cool. Business or pleasure? Would have been good to buy you a beer or two - would be the least I could do for all time this extension has saved me! Well hopefully you get some time to pop down to the beach while you're here and enjoy some of our warm weather. 😄

**Comment by codeandcats** [comment]
Hey Mike, I had some time this morning to look at this and seem to have a working solution. See [PR](https://github.com/MikeRogers0/LivePage/pull/71).

I didn't bother with a barebones example to replicate the issue but instead testing it out in a project I'm working on.

You should be able to replicate it by cloning [this](https://github.com/grammatic/grammatic-ide).

Then run:
```
npm install
npm run build:watch
```

Open `index.html` in your browser.

Then make any changes to the web app source.

Cheers
