### ISSUE TITLE
Capture 404 errors so they don't appear in terminal

### ISSUE THREAD

**Issue by MikeRogers0** [MikeRogers0/LivePage#72]
A user saw the errors and emailed me (The email was difficult to understand), I think they were linking to missing files & didn't understand the error message.

Ideally I'd like to move all the LivePage stuff to be out of the users view so they can focus on building.

**Comment by ArtOfCode-** [comment]
Query: Is this desirable? I only ask because if a file can't be found, I want to know about that when I'm building the app, which I find out from the console. The only alternative is no error, in which case I end up with an unstyled page with no obvious errors.

**Comment by MikeRogers0** [comment]
@ArtOfCode- I totally agree with you! I'm going to close this bug :)
