### ISSUE TITLE
Split Ignore inline JavaScript & hidden fields in HTML into two different options

### ISSUE THREAD

**Issue by chrisjj** [MikeRogers0/LivePage#74]
I think the Advanced Settings Ignore options should be off by default (currently on).

In particular I think "[x] Ignore inline JavaScript & hidden fields in HTML" makes no sense at all as a default.

**Comment by MikeRogers0** [comment]
I disagree, options such as "Ignore comments in HTML" & "Skip external resources such as googleapis.com or CDNs" are sensible defaults to have enabled.

> Ignore inline JavaScript & hidden fields in HTML

This was enabled by default for two reasons:
1. Lots of webpages have CSRF tokens stored in hidden fields which change every page load (and hence would trigger a page reload), to stop bots submitting forms.
2. Inline javascript was added as a number of users emailed me complaining of constant reloading, caused by storing the current DateTime somewhere in inline JS. 

What was the exact issue them being enabled caused you?

**Comment by chrisjj** [comment]
> options such as "Ignore comments in HTML" & "Skip external resources such as googleapis.com or CDNs" are sensible defaults to have enabled.

I was referring just to the Ignore options.

> What was the exact issue them being enabled caused you?

The issue caused here by these Ignores enabled _by default_ was that inline Javascript changes. were beign ignored despite what LivePage says on the tin:

"LivePage is a developer tool which reloads website resources (such as CSS, HTML and JavaScript) as they update on the server, so you are always looking at the most up-to-date version of a web page. It can make developing websites a lot faster, by helping productivity."

> Lots of webpages have CSRF tokens stored in hidden fields which change every page load
> (and hence would trigger a page reload), to stop bots submitting forms

> Inline javascript was added as a number of users emailed me complaining of constant
> reloading, caused by storing the current DateTime somewhere in inline JS.

So, LP was working as designed. And (in the absence of a finer-grained ignore) the appropriate solution is surely for that user to enable JS Ignore... having accepted the side-effect of ignoring any manual JS changes.

I think the user who finds unexplained update fails upon manual JS changes is less likely to complain, and less likely to realise LP is not doing what it was sold to do only becasue of a default setting. He's more likely to assume the extension is poor, as did I, initially.

**Comment by MikeRogers0** [comment]
Ok that seems reasonable, I'll break out that option into:

- "Ignore inline javascript" - Disabled by default
- "Ignore hidden HTML elements & comments" - Enabled by default

**Comment by chrisjj** [comment]
Mike,

> I'll think the best solution is to break out "Ignore inline JavaScript & hidden fields in HTML" into:
> 
> "Ignore inline javascript" - Disabled by default
> "Ignore hidden HTML elements & comments" - Enabled by default
> 
> I think this should solve your use case while still handling the CSRF token issue 

Sounds good to me.

And I think 'Ignore hidden HTML elements' (taking that to refer just to elements having type='hidden') shouldn't operate when they aren't hidden from view i.e. in view-source:.

BTW, I think "Monitor adhoc files using:"" would be better worded "Monitor files specified using:". The files probably are aren't adhoc ;-) .

**Comment by MikeRogers0** [comment]
BTW, I think "Monitor adhoc files using:"" would be better worded "Monitor files specified using:". The files probably are aren't adhoc ;-) .

I like that wording! I've added it as its own ticket :)

**Comment by MikeRogers0** [comment]
PR in #78 will review tomorrow with fresh eyes.

**Comment by MikeRogers0** [comment]
This is now in master, aiming to have this rolled out by the end of the month :)
