### ISSUE TITLE
V2.3.2 "Cannot read property 'refresh_rate' of undefined"

### ISSUE THREAD

**Issue by chrisjj** [MikeRogers0/LivePage#79]
I'm getting this error http://i.imgur.com/f38l1WM.png when I click my page's link:

`<a id='se1' onclick="searchex('se1')" href='#'>D'Arienzo</a>`

I'd rather not post the full page source.

**Comment by MikeRogers0** [comment]
Hi @chrisjj Is this happening on every page you visit & immediately after you enable LivePage?

**Comment by chrisjj** [comment]
No.

**Comment by MikeRogers0** [comment]
I'm struggling to reproduce this error @chrisjj would you be able to email me more details (me@mikerogers.io) so I can debug?

**Comment by chrisjj** [comment]
Mike, I've emailed you a sample HTML file. When I open this in Chrome, enable LP (options http://i.imgur.com/chw45j0.png , http://i.imgur.com/blKCELd.png ) , open console, and click the link **D'Arienzo**, I get the error: http://i.imgur.com/qieMASW.png .
