### ISSUE TITLE
Settings screen broken

### ISSUE THREAD

**Issue by arechsteiner** [MikeRogers0/LivePage#82]
I just noticed that LivePage is not working anymore for some reason, and went to see the options page. It looks like something went wrong:

![screenshot_1](https://cloud.githubusercontent.com/assets/1199486/21750563/3f1f8976-d5b6-11e6-86bc-24675db40bf6.png)

I've tried restarting chrome and removing/reinstalling LivePage. Nothing seems to help.

Any advice on how to troubleshoot this?

**Comment by MikeRogers0** [comment]
I'm 100% sorry, when deploying the latest version I linked a file incorrectly. I've deployed a fix & restarting your browser will fix the issue.

I'm working on improving the processes my end ( #83 & #84 ) to make building the extension & verifying silly mistakes like this don't make it to production in the future.

**Comment by arechsteiner** [comment]
It's working again. Thanks for the quick fix.

I like to use a checklists that I go through before/after releasing stuff. It provides some peace of mind as well as preventing screw-ups. Automation is also good of course.
