### ISSUE TITLE
Please support chrome:// protocol

### ISSUE THREAD

**Issue by chrisjj** [MikeRogers0/LivePage#86]
Current attempting to engage LP on e.g. chrome://history/ fails: http://i.imgur.com/qDzWEUT.png .

If it is not much work, please remedy this. That will let me see a like History list while I'm debugging JS code that alters it e.g. using window.location hash =.

Thanks.

**Comment by MikeRogers0** [comment]
I'm open to adding an option to disable the protocol restriction in a future version behind a flag in the advanced settings. It might take me time to implement (2.5.0 is my current focus), but giving users more control seems good.

**Comment by chrisjj** [comment]
Thanks Mike.

**Comment by MikeRogers0** [comment]
I looked into implementing this feature this evening. It looks like Chrome does not allow extensions to run on the `chrome://` URLs (also called WebUI) for security reasons.

**Comment by chrisjj** [comment]
OK. Thanks.
