### ISSUE TITLE
Feature request: option to disable hash part in page ID

### ISSUE THREAD

**Issue by chrisjj** [MikeRogers0/LivePage#87]
I'm debugging a page using anchors i.e. some link clicks change just the URL hash part.

Each new hash part value causes LP to disable. It seems LP includes the hash part in identifying the page.

I'd like an option to disable this. I'd like it disabled by default, though maybe a few others would not.

**Comment by MikeRogers0** [comment]
What are your settings for:
 - Run LivePage on entire domains
 - Ignore URL anchors
Set to?

**Comment by chrisjj** [comment]
I wouldn't like to guess :)

![image](https://cloud.githubusercontent.com/assets/6157073/21766010/eb7d22b6-d663-11e6-95f8-f648e6d4c511.png)

However switching from 2.4.1 production variant to 2.4.2 development variant I find the problem has disappeared... and I see option '[x] Ignore URL anchors'. Great!

FWIW, I see '[ ] Run LivePage on entire domains'. From the wording of that label and the fact my page is file:// e.g. no domain, I'd not expect that option to have any effect.
