### ISSUE TITLE
ERR_SOCKET_NOT_CONNECTED on Server Restart

### ISSUE THREAD

**Issue by timsayshey** [MikeRogers0/LivePage#88]
Throws an error when I restart my server in the background:
```
GET http://localhost/?livePage=1484678762655 net::ERR_SOCKET_NOT_CONNECTED
LiveResource.check	@	live_resource.js:71
livePage.check	@	livepage.js:236
livePage.checkBatch	@	livepage.js:219
livePage.scanPage	@	livepage.js:44
(anonymous)	@	livepage.js:248

```
It should catch the error, not stop the entire extension. Please advise.

**Comment by MikeRogers0** [comment]
Thank you @timsayshey ! If we cross paths (I am sometimes in the US) make sure to make me buy you a beverage 👍

**Comment by MikeRogers0** [comment]
This has now been deployed to production, thank you again!

**Comment by MikeRogers0** [comment]
Also @timsayshey thank you for the kind review on the chrome store, it really helps me :)
