### ISSUE TITLE
"file:// protocol needs enabling." - Enabled already

### ISSUE THREAD

**Issue by vincegio** [MikeRogers0/LivePage#91]
> Sorry, the file:// protocol needs enabling. Please check the "Allow access to file URLs" for LivePage on the extensions page (chrome://extensions/).

It's enabled, but nothing. Restarted browser and toggled the extension.

**Comment by MikeRogers0** [comment]
This is a duplicate of #86.

In this case, `chrome://` is the protocol & it's not supported. I'll update the copy to make it clearer.
