### ISSUE TITLE
window.sessionStorage error thrown on file:// protocol

### ISSUE THREAD

**Issue by gromimol** [MikeRogers0/LivePage#93]
Don't work LivePage after 3 month. Before LivePage work awesome, but now not want. Allow access to FilesURLs - active

**Comment by MikeRogers0** [comment]
OK, not much has changed in the last 3 months with LivePage.
Questions to help me debug:
1. What version are you using?
2. What is the URL you are trying to use LivePage on? Can you send me what you're working on so I can recreate error locally?
3. Are there any errors in the chrome console when you try to run LivePage?

Thanks!

**Comment by gromimol** [comment]
Thank’s for your quick answer! Sorry for my English))
1. Today I’m reinstalled LivePage. Version - 2.4.3 now
2. I’m using only file// URLs
3. Yes, console have error http://joxi.ru/l2ZRPkQFwRxKv2 <http://joxi.ru/l2ZRPkQFwRxKv2>
maybe for you better work  through TeamViewer?
> 21 февр. 2017 г., в 10:52, Mike Rogers <notifications@github.com> написал(а):
> 
> OK, not much has changed in the last 3 months with LivePage.
> Questions to help me debug:

**Comment by MikeRogers0** [comment]
Ok, I understand the error. I'm working on a fix now.

**Comment by gromimol** [comment]
Thanks

**Comment by MikeRogers0** [comment]
@gromimol I've just deployed a patch for this error to the Chrome Web Store. It will take about 1 hour to be available in the Chrome Web Store, then rolled out automatically over the next 24h.

Thank you for reporting this! I'm sure this would have affected a lot of other users :)

**Comment by gromimol** [comment]
If i understand correct, the problem in Chrome? Because , i’m reinstalled LivePage again and see the same problem

**Comment by gromimol** [comment]
Thanks for your work!!!

**Comment by MikeRogers0** [comment]
@gromimol 

> If i understand correct, the problem in Chrome? 
Something changed in chrome recently I think, which caused the error. 

> i’m reinstalled LivePage again and see the same problem
The new version will be available in the Chrome Store in an hour, when you reinstall then it'll work again :)

**Comment by gromimol** [comment]
Mike, you best of the best!!! Your speed response and a solution problem!!! Cool!! And LivePage really good product!
