### ISSUE TITLE
Antimalware notification

### ISSUE THREAD

**Issue by masterkadaj** [MikeRogers0/LivePage#95]
Good day!
It's an issue or misunderstanding I suppose, still my Malwarebytes AdAware tells me that this extension is a malware, I understand, that this extension monitors local computer's file system, but, are you planning to do something about that notification? (I don't don't know, may be contact with Malwarebytes, check the code or something like that).

**Comment by MikeRogers0** [comment]
I'm going to get in contact with Malwarebytes AdAware to find out what is trigging this warning. You can see [all the source code](https://github.com/MikeRogers0/LivePage) that goes into this extension and there is 100% nothing mischievous in there.

**Comment by MikeRogers0** [comment]
@masterkadaj Could you provide me more details of the notification? For example, what was the name of the threat it thought LivePage contained? Anything to help me debug what is triggering Malwarebytes would be helpful :)

**Comment by MikeRogers0** [comment]
I haven't had any more reports of this alert & Malwarebytes failed to respond to my request. I'm closing this off.
