### ISSUE TITLE
No reload on js file included in body

### ISSUE THREAD

**Issue by matchwood** [MikeRogers0/LivePage#97]
When I include a javascript file in <head> the plugin polls as expected, but when I move the same tag to <body> the plugin doesn't seem to pick it up. I'm guessing it might be a timing issue - perhaps LivePage is running for the first time too early?

I am using Chrome on Ubuntu Version 54.0.2840.71 (64-bit).

**Comment by MikeRogers0** [comment]
Can you give me a code example? I'm struggling to visualise what you mean.

**Comment by matchwood** [comment]
Sure, I mean like this:
```
    <!doctype html>
       <html lang="en">
       <head>
        <script src="/js/doestrigger.js"></script>
       </head>
      <body>
         <script src="/js/doesnottrigger.js"></script>
      </body>
    </html>

```
LivePage generates GET requests for doestrigger.js, but doesn't generate any for doesnottrigger.js. 

After playing around a bit I'm pretty sure that it is a timing issue - the file I'm including in the body (`doesnottrigger.js`) takes a few seconds to finish running when it is first loaded. If I include the file but stop it from running then LivePage works as expected.

**Comment by MikeRogers0** [comment]
Ok awesome! I'll try and recreate this bug my end & work on a fix :)

Thank for you reporting this to me!

**Comment by matchwood** [comment]
Many thanks. I can provide the original failing file if you like (though it it is a timing issue then it may not replicate on your machine in any case).

**Comment by MikeRogers0** [comment]
That would be incredible! My email is me@mikerogers.io :)

**Comment by matchwood** [comment]
Thanks for looking into it - emailed you just now.

**Comment by MikeRogers0** [comment]
Just a heads up, I haven't forgotten about this. I'm still looking into it :)
